[project]
name = "quote-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = 'BELLBU\bellb', email = "bellbu@naver.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mcp[cli]>=2.3.0",
]

[project.scripts]
quote-cli = "quote_cli:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
